### ISSUE TITLE
No such file or directory: '../data/generated/images_transformed.csv'

### ISSUE THREAD

**Issue by muhammadzulfanazhari** [Anmol-Singh-Jaggi/Sign-Language-Recognition#2]
when I execute run.sh, I get this message. Did you have any idea?

**Comment by Anmol-Singh-Jaggi** [comment]
At what step do you get this?

**Comment by muhammadzulfanazhari** [comment]
It has worked now. But, I got the problem at train_model.py. The error message is as following
Training the model...
Traceback (most recent call last):
  File "./train_model.py", line 129, in <module>
    main()
  File "./train_model.py", line 104, in main
    training_images, training_labels)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py", line 765, in fit
    X, y = check_X_y(X, y, "csr", multi_output=True)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by Anmol-Singh-Jaggi** [comment]
The array is empty, which means the data is not being read/generated properly.

**Comment by muhammadzulfanazhari** [comment]
so what is the solution?

**Comment by Anmol-Singh-Jaggi** [comment]
Have you downloaded the training images in the appropriate directory?

**Comment by Anmol-Singh-Jaggi** [comment]
Anyway, I'll make some changes so that others are able to directly use the model generated by the training data used by me.

**Comment by Anmol-Singh-Jaggi** [comment]
I've done the changes. Try now.

**Comment by muhammadzulfanazhari** [comment]
Sorry for late respond, I've downloaded the training images. 
Ok, I will try it

**Comment by muhammadzulfanazhari** [comment]
both of run.sh and run_quick.sh still do not work. 
Error message:
../data/images/test/F/001.jpg	F
Resizing image to 100...
Done!
Making background black...
Done!
Making skin white...
Done!
Removing OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvDestroyAllWindows, file /home/mitlab-server2/Software/opencv/opencv-cuda8/opencv/modules/highgui/src/window.cpp, line 554
arm...
Done!
Drawing contour around white color...
Error while applying image transformation on image path '../data/images/test/F/001.jpg' with the following exception trace:
Traceback (most recent call last):
  File "./predict_from_file.py", line 32, in main
    frame = apply_image_transformation(frame)
  File "/home/zulfan/SLR/Sign-Language-Recognition/Sign-Language-Recognition/code/common/image_transformation.py", line 171, in apply_image_transformation
    frame, contour_dimensions = draw_contours(frame)
  File "/home/zulfan/SLR/Sign-Language-Recognition/Sign-Language-Recognition/code/common/image_transformation.py", line 122, in draw_contours
    frame, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack

Traceback (most recent call last):
  File "./predict_from_file.py", line 52, in <module>
    main()
  File "./predict_from_file.py", line 47, in main
    cv2.destroyAllWindows()
cv2.error: /home/mitlab-server2/Software/opencv/opencv-cuda8/opencv/modules/highgui/src/window.cpp:554: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvDestroyAllWindows

**Comment by Anmol-Singh-Jaggi** [comment]
It looks like the opencv version you are using is incompatible with the code.

**Comment by Anmol-Singh-Jaggi** [comment]
After a **long** wait, I have made significant changes to the codebase:  
 - Updated to Python3.
 - Updated all the dependencies (scipy/numpy/opencv etc.)
 - Locked the dependencies graph using `pipenv`.  
   (This should solve most of the problems faced by new users)
 - Added logging.
 - Added progress bar.
 - Simplified project setup and the Readme.
 - Minor bug fixes. 

Please try it again now; feedback is highly appreciated! :)
