### ISSUE TITLE
Error when I run python train_model.py svm

### ISSUE THREAD

**Issue by gofornaman** [Anmol-Singh-Jaggi/Sign-Language-Recognition#5]
this is is the error 

**ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample**.

i just want to implement predict from camera using your serialized model, so if you mention the steps for that it will be really helpful thanks

**Comment by abbas518** [comment]
give the classifier a 2D array, that is by reshaping it using .reshape(1,-1)

**Comment by Anmol-Singh-Jaggi** [comment]
After a **long** wait, I have made significant changes to the codebase:  
 - Updated to Python3.
 - Updated all the dependencies (scipy/numpy/opencv etc.)
 - Locked the dependencies graph using `pipenv`.  
   (This should solve most of the problems faced by new users)
 - Added logging.
 - Added progress bar.
 - Simplified project setup and the Readme.
 - Minor bug fixes. 

Please try it again now; feedback is highly appreciated! :)
