### ISSUE TITLE
predict from camera giving random outputs

### ISSUE THREAD

**Issue by akash1725** [Anmol-Singh-Jaggi/Sign-Language-Recognition#6]
I was trying to run the code.  Everything worked fine for me till predict_from_file. When I am using predict_from_camera it is giving random outputs. I just wanted to ask if there is some restriction on things like distance between camera and hand or any other such similar restriction.

**Comment by Anmol-Singh-Jaggi** [comment]
In fact I had a similar experience. I think the background wall color and hand orientation are the reasons to blame. Will have to debug further to find out what's happening.
